<?php

//  Default language
$arrLang['en']['reset']						= 'RESET';
$arrLang['en']['update']					= 'UPDATE';

$arrLang['en']['us_usernameLbl']			= 'Username';
$arrLang['en']['us_oldpasswordLbl']			= 'Old Password';
$arrLang['en']['us_passwordLbl']			= 'New Password';
$arrLang['en']['us_confpasswordLbl']		= 'Confirm Password';
$arrLang['en']['Recordupdated']				= 'Password updated successfully';
$arrLang['en']['Nomatch']					= 'Old Password Incorrect';
?>