<?php 

//  Default language
$arrLang['en']['add']						= 'ADD';
$arrLang['en']['save']						= 'Save';
$arrLang['en']['reset']						= 'RESET';
$arrLang['en']['delete']					= 'Delete';
$arrLang['en']['back']						= 'Back';
$arrLang['en']['search']					= 'SEARCH';
$arrLang['en']['clear']						= 'CLEAR';
$arrLang['en']['open']						= 'Open';
$arrLang['en']['view']						= 'View';
$arrLang['en']['viewAll']					= 'View All';
$arrLang['en']['refresh']					= 'Refresh';
$arrLang['en']['remove']					= 'Remove';
$arrLang['en']['checkallrecord']			= 'Check all records';
$arrLang['en']['invertSelection']			= 'Invert Selection';
$arrLang['en']['selectAll']					= 'Select All';
$arrLang['en']['unSelectAll']				= 'Unselect All';
$arrLang['en']['deleteSelected']			= 'Delete Selected';
$arrLang['en']['deletedConfirmMsg']			= 'Are you sure you want to perform this operation?';
$arrLang['en']['removeConfirmImg']			= 'Are you sure you want to remove Image';
$arrLang['en']['removeConfirmDoc']			= 'Are you sure you want to remove Document';
$arrLang['en']['newRecord']					= 'New Record';
$arrLang['en']['noResultFound']				= 'No Result Found';
$arrLang['en']['update']					= 'UPDATE';
$arrLang['en']['delete']					= 'DELETE';
$arrLang['en']['view']						= 'View';
$arrLang['en']['remove']					= 'Remove';
$arrLang['en']['genTableSelect']			= '--- Select ---';
$arrLang['en']['yes']						= 'Yes';
$arrLang['en']['no']						= 'No';
$arrLang['en']['all']						= 'All';
$arrLang['en']['requiredPhrase']			= 'Required fields are indicated by ';
$arrLang['en']['describerExist']			= 'act_title value already exists!';
$arrLang['en']['previous']					= 'Prev';
$arrLang['en']['next']						= 'Next';
$arrLang['en']['first']						= 'First';
$arrLang['en']['last']						= 'Last';
$arrLang['en']['total']						= 'Total';
$arrLang['en']['page']						= 'Page';
$arrLang['en']['populateTable']				= 'You must first populate table';
$arrLang['en']['invalidParam']				= 'Invalid argument passed!';
$arrLang['en']['addSuccess']				= 'Record added successfully';
$arrLang['en']['modifySuccess']				= 'Record modified successfully';
$arrLang['en']['backToForm']				= 'Back to search form';
$arrLang['en']['Recordadded']				= 'Record added successfully...';
$arrLang['en']['Recordupdated']				= 'Record updated successfully...';
$arrLang['en']['Recorddeleted']				= 'Record deleted successfully...';
$arrLang['en']['BOApplication']				= 'Back Office Application';
$arrLang['en']['addnew']					= 'ADD NEW';

//specific fields 
$arrLang['en']['sl_id']						= 'sl_id';
$arrLang['en']['sl_title']					= 'Title';
$arrLang['en']['sl_img']					= 'Image';
$arrLang['en']['sl_desc']					= 'Description';
$arrLang['en']['sl_order']					= 'Order';
$arrLang['en']['sl_link']					= 'Link';
$arrLang['en']['sl_published']				= 'Published';
$arrLang['en']['sl_cruser']					= 'sl_cruser';
$arrLang['en']['sl_crdate']					= 'sl_crdate';
$arrLang['en']['sl_mduser']					= 'sl_mduser';
$arrLang['en']['sl_mddate']					= 'sl_mddate';

 
?>