<?php 

//  Default language
$arrLang['en']['add']						= 'ADD';
$arrLang['en']['save']						= 'Save';
$arrLang['en']['reset']						= 'RESET';
$arrLang['en']['delete']					= 'Delete';
$arrLang['en']['back']						= 'Back';
$arrLang['en']['search']					= 'SEARCH';
$arrLang['en']['clear']						= 'CLEAR';
$arrLang['en']['open']						= 'Open';
$arrLang['en']['view']						= 'View';
$arrLang['en']['viewAll']					= 'View All';
$arrLang['en']['refresh']					= 'Refresh';
$arrLang['en']['remove']					= 'Remove';
$arrLang['en']['checkallrecord']			= 'Check all records';
$arrLang['en']['invertSelection']			= 'Invert Selection';
$arrLang['en']['selectAll']					= 'Select All';
$arrLang['en']['unSelectAll']				= 'Unselect All';
$arrLang['en']['deleteSelected']			= 'Delete Selected';
$arrLang['en']['deletedConfirmMsg']			= 'Are you sure you want to perform this operation?';
$arrLang['en']['removeConfirmImg']			= 'Are you sure you want to remove Image';
$arrLang['en']['removeConfirmDoc']			= 'Are you sure you want to remove Document';
$arrLang['en']['newRecord']					= 'New Record';
$arrLang['en']['noResultFound']				= 'No Result Found';
$arrLang['en']['update']					= 'UPDATE';
$arrLang['en']['delete']					= 'DELETE';
$arrLang['en']['view']						= 'View';
$arrLang['en']['remove']					= 'Remove';
$arrLang['en']['genTableSelect']			= '--- Select ---';
$arrLang['en']['yes']						= 'Yes';
$arrLang['en']['no']						= 'No';
$arrLang['en']['all']						= 'All';
$arrLang['en']['requiredPhrase']			= 'Required fields are indicated by ';
$arrLang['en']['describerExist']			= 'act_title value already exists!';
$arrLang['en']['previous']					= 'Prev';
$arrLang['en']['next']						= 'Next';
$arrLang['en']['first']						= 'First';
$arrLang['en']['last']						= 'Last';
$arrLang['en']['total']						= 'Total';
$arrLang['en']['page']						= 'Page';
$arrLang['en']['populateTable']				= 'You must first populate table';
$arrLang['en']['invalidParam']				= 'Invalid argument passed!';
$arrLang['en']['addSuccess']				= 'Record added successfully';
$arrLang['en']['modifySuccess']				= 'Record modified successfully';
$arrLang['en']['backToForm']				= 'Back to search form';
$arrLang['en']['Recordadded']				= 'Record added successfully...';
$arrLang['en']['Recordupdated']				= 'Record updated successfully...';
$arrLang['en']['Recorddeleted']				= 'Record deleted successfully...';
$arrLang['en']['BOApplication']				= 'Back Office Application';
$arrLang['en']['addnew']					= 'ADD NEW';

//specific fields 
$arrLang['en']['us_id']				= 'us_id';
$arrLang['en']['us_lname']				= 'Last';
$arrLang['en']['us_fname']				= 'First';
$arrLang['en']['us_img']				= 'Avatar';
$arrLang['en']['us_dob']				= 'Date Of Birth';
$arrLang['en']['us_address']				= 'Address';
$arrLang['en']['us_phone']				= 'Phone';
$arrLang['en']['us_mobile']				= 'Mobile';
$arrLang['en']['us_email']				= 'Email';
$arrLang['en']['us_username']				= 'Username';
$arrLang['en']['us_password']				= 'Password';
$arrLang['en']['us_isactive']				= 'Active';
$arrLang['en']['us_gr_id']				= 'Group';
$arrLang['en']['us_cruser']				= 'us_cruser';
$arrLang['en']['us_crdate']				= 'us_crdate';
$arrLang['en']['us_mduser']				= 'us_mduser';
$arrLang['en']['us_mddate']				= 'us_mddate';

 
?>